# Generated by Django 5.2.7 on 2025-11-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('disk', models.CharField(blank=True, max_length=255, null=True)),
                ('mem', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Agent名称')),
                ('version', models.CharField(blank=True, max_length=64, verbose_name='版本')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='状态')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最近心跳时间')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='cmdb.host', verbose_name='关联主机')),
            ],
        ),
    ]
